# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Run tests with coverage
      run: go test -v ./... -coverprofile=coverage.out

    - name: Show coverage report
      run: go tool cover -func=coverage.out

    - name: Enforce minimum 80% test coverage
      run: |
        threshold=80
        total=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
        echo "Current test coverage: $total%"
        if (( $(echo "$total < $threshold" | bc -l) )); then
          echo "❌ Coverage $total% is below threshold ($threshold%)"
          exit 1
        else
          echo "✅ Coverage is sufficient"
        fi
